(define (showmove src dst)
  (begin (display "Move Mary from ")
         (display src)
         (display " to ")
         (display dst)
         (display ".")
         (newline)))
(define (hanoi n src tmp dst)
  (if (= n 1)
      (showmove src dst)
      (begin (hanoi (- n 1) src tmp dst)
                      (hanoi 1 src dst tmp)
                      (hanoi (- n 1) tmp dst src))))
(hanoi 3 'Earth 'Purgatory 'Heaven)